apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-model-rf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # What happens to the PV after the PVC is deleted
  hostPath:
    path: /data/model_rf

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-model-xgb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # What happens to the PV after the PVC is deleted
  hostPath:
    path: /data/model_xgb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-training-data
spec:
  capacity:
    storage: 1Gi  # Define the storage size
  accessModes:
    - ReadWriteOnce  # Define the access mode (e.g., ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # What happens to the PV after the PVC is deleted
  hostPath:  # Example of using local storage; replace with your storage backend
    path: /data/training_data 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-validation-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/validation_data 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-metrics-rf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: /data/saved_metrics/rf  # Directory on the host machine

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-metrics-xgb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: /data/saved_metrics/xgb  # Directory on the host machine

