apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-metrics-xgb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: /data/saved_metrics/xgb  # Directory on the host machine
