apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-metrics-rf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: /data/saved_metrics/rf  # Directory on the host machine
