apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-model-xgb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # What happens to the PV after the PVC is deleted
  hostPath:
    path: /data/model_xgb



