apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-training-data
spec:
  capacity:
    storage: 1Gi  # Define the storage size
  accessModes:
    - ReadWriteOnce  # Define the access mode (e.g., ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # What happens to the PV after the PVC is deleted
  hostPath:  # Example of using local storage; replace with your storage backend
    path: /data/training_data 

