apiVersion: batch/v1
kind: Job
metadata:
  name: data-modelling-job
spec:
  completions: 1  # Number of successful completions needed
  parallelism: 1  # Number of pods to run concurrently
  backoffLimit: 4  # Number of retries before considering the Job failed
  template:
    metadata:
      labels:
        app: data-modelling
    spec:
      restartPolicy: Never
      containers:
      - name: data-modelling
        image: lazerhorn/data_modelling:latestv3
        volumeMounts:
        - name: training-data
          mountPath: /data/training_data
        - name: validation-data
          mountPath: /data/validation_data
        - name: model-rf
          mountPath: /data/model_rf
        - name: model-xgb
          mountPath: /data/model_xgb
        - name: shared-config
          mountPath: /data/config
      volumes:
      - name: training-data
        persistentVolumeClaim:
          claimName: pvc-training-data
      - name: validation-data
        persistentVolumeClaim:
          claimName: pvc-validation-data
      - name: model-rf
        persistentVolumeClaim:
          claimName: pvc-model-rf
      - name: model-xgb
        persistentVolumeClaim:
          claimName: pvc-model-xgb
      - name: shared-config
        configMap:
          name: shared-config
