apiVersion: batch/v1
kind: Job
metadata:
  name: model-inference-job
spec:
  completions: 1  # Number of successful completions needed
  parallelism: 1  # Number of pods to run concurrently
  backoffLimit: 4  # Number of retries before considering the Job failed
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      restartPolicy: Never
      containers:
      - name: model-inference
        image: lazerhorn/model_inference:latestv2
        volumeMounts:
        - name: validation-data
          mountPath: /data/validation_data
        - name: model-rf
          mountPath: /data/model_rf
        - name: model-xgb
          mountPath: /data/model_xgb
        - name: shared-config
          mountPath: /data/config
        - name: inference-rf
          mountPath: /data/saved_metrics/rf
        - name: inference-xgb
          mountPath: /data/saved_metrics/xgb
      volumes:
      - name: inference-xgb
        persistentVolumeClaim:
          claimName: pvc-metrics-xgb
      - name: inference-rf
        persistentVolumeClaim:
          claimName: pvc-metrics-rf
      - name: validation-data
        persistentVolumeClaim:
          claimName: pvc-validation-data
      - name: model-rf
        persistentVolumeClaim:
          claimName: pvc-model-rf
      - name: model-xgb
        persistentVolumeClaim:
          claimName: pvc-model-xgb
      - name: shared-config
        configMap:
          name: shared-config
