apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-modelling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-modelling
  progressDeadlineSeconds: 600  # Maximum time in seconds for a deployment to make progress before it is considered failed
  minReadySeconds: 30           # Minimum time in seconds for a pod to be ready before it is considered available
  revisionHistoryLimit: 5       # Number of old ReplicaSets to retain for rollback purposes
  template:
    metadata:
      labels:
        app: data-modelling
    spec:
      containers:
      - name: data-modelling
        image: lazerhorn/data_modelling:latestv4
        resources:
          requests:
            memory: "1Gi"      # Minimum memory required
            cpu: "1"          # Minimum CPU required
          limits:
            memory: "2Gi"        # Maximum memory allowed
            cpu: "2"          # Maximum CPU allowed
        volumeMounts:
        - name: training-data
          mountPath: /data/training_data
        - name: validation-data
          mountPath: /data/validation_data
        - name: model-rf
          mountPath: /data/model_rf
        - name: model-xgb
          mountPath: /data/model_xgb
        - name: shared-config
          mountPath: /data/config
      volumes:
      - name: training-data
        persistentVolumeClaim:
          claimName: pvc-training-data
      - name: validation-data
        persistentVolumeClaim:
          claimName: pvc-validation-data
      - name: model-rf
        persistentVolumeClaim:
          claimName: pvc-model-rf
      - name: model-xgb
        persistentVolumeClaim:
          claimName: pvc-model-xgb
      - name: shared-config
        configMap:
          name: shared-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
