apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing
  progressDeadlineSeconds: 600  # Maximum time in seconds for a deployment to make progress before it is considered failed
  minReadySeconds: 120          # Minimum time in seconds for a pod to be ready before it is considered available
  revisionHistoryLimit: 5       # Number of old ReplicaSets to retain for rollback purposes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1               # Maximum number of pods that can be created over the desired number of pods
      maxUnavailable: 1         # Maximum number of pods that can be unavailable during the update process
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      containers:
      - name: data-processing
        image: lazerhorn/data_processing:latestv5
        resources:
          requests:
            memory: "512Mi"      # Minimum memory required
            cpu: "250m"          # Minimum CPU required
          limits:
            memory: "1Gi"        # Maximum memory allowed
            cpu: "500m"          # Maximum CPU allowed
        volumeMounts:
        - name: raw-data
          mountPath: /data/raw
        - name: training-data
          mountPath: /data/training_data
        - name: validation-data
          mountPath: /data/validation_data
        - name: shared-config
          mountPath: /data/config
            
      volumes:
      - name: raw-data
        hostPath:
          path: /data/raw
      - name: training-data
        persistentVolumeClaim:
          claimName: pvc-training-data
      - name: validation-data
        persistentVolumeClaim:
          claimName: pvc-validation-data
      - name: shared-config
        configMap:
          name: shared-config
