apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-inference
  progressDeadlineSeconds: 600  # Maximum time in seconds for a deployment to make progress before it is considered failed
  minReadySeconds: 60           # Minimum time in seconds for a pod to be ready before it is considered available
  revisionHistoryLimit: 5       # Number of old ReplicaSets to retain for rollback purposes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1               # Maximum number of pods that can be created over the desired number of pods
      maxUnavailable: 1         # Maximum number of pods that can be unavailable during the update process
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
      - name: model-inference
        image: lazerhorn/model_inference:latestv6
        resources:
          requests:
            memory: "512Mi"        # Minimum memory required
            cpu: "250m"          # Minimum CPU required
          limits:
            memory: "2Gi"        # Maximum memory allowed
            cpu: "500m"             # Maximum CPU allowed (1 full CPU core)
        volumeMounts:
        - name: validation-data
          mountPath: /data/validation_data
        - name: model-rf
          mountPath: /data/model_rf
        - name: model-xgb
          mountPath: /data/model_xgb
        - name: shared-config
          mountPath: /data/config
        - name: inference-rf
          mountPath: /data/saved_metrics/rf
        - name: inference-xgb
          mountPath: /data/saved_metrics/xgb

      volumes:
      - name: inference-xgb
        persistentVolumeClaim:
          claimName: pvc-metrics-xgb
      - name: inference-rf
        persistentVolumeClaim:
          claimName: pvc-metrics-rf
      - name: validation-data
        persistentVolumeClaim:
          claimName: pvc-validation-data
      - name: model-rf
        persistentVolumeClaim:
          claimName: pvc-model-rf
      - name: model-xgb
        persistentVolumeClaim:
          claimName: pvc-model-xgb
      - name: shared-config
        configMap:
          name: shared-config
