apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-model-rf
spec:
  storageClassName: ""  # Explicitly set no storage class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-model-rf  # Bind this PVC to the specific PV