apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-model-xgb
spec:
  storageClassName: ""  # Explicitly set no storage class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-model-xgb  # Bind this PVC to the specific PV

<<<<<<< HEAD
=======


>>>>>>> 62278d770fb064529f3f88a132c9c7ecb56d9cd0
