apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-metrics-xgb
spec:
  storageClassName: ""  # Explicitly set no storage class
  accessModes:
    - ReadWriteMany  # Should match the access mode of the PV
  resources:
    requests:
      storage: 1Gi  # Requesting 10Gi of storage
  volumeName: pv-metrics-xgb
