apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-validation-data
spec:
  storageClassName: ""  # Explicitly set no storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-validation-data  # Bind this PVC to the specific PV